[package]
name = "clientapp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.18"
gloo-render = "0.1.0"
wasm-bindgen = "0.2.76"
js-sys = "0.3.53"
yew-router = "0.15.0"
serde = "1.0.129"

[dependencies.web-sys]
version = "0.3"
features = [
  'HtmlCanvasElement',
  'WebGlBuffer',
  'WebGlProgram',
  'WebGlRenderingContext',
  'WebGlShader',
  'WebGlUniformLocation',
]